# Generated by Django 6.1.1 on 2026-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepzdoniczkami', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Przelew bankowy'), ('card', 'Karta płatnicza'), ('cash_on_delivery', 'Pobranie')], default='transfer', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Odbiór osobisty'), ('courier', 'Kurier'), ('parcel', 'Paczkomat')], default='courier', max_length=30),
        ),
    ]
