# Generated by Django 6.1.1 on 2026-09-25 19:14

from django.db import migrations, models


def reserve_existing_pending_orders(apps, schema_editor):
    Order = apps.get_model("sklepzdoniczkami", "Order")
    OrderItem = apps.get_model("sklepzdoniczkami", "OrderItem")
    Product = apps.get_model("sklepzdoniczkami", "Product")
    database = schema_editor.connection.alias

    for order in (
        Order.objects.using(database)
        .filter(status="pending", is_paid=False)
        .order_by("created_at", "pk")
        .iterator()
    ):
        items = list(
            OrderItem.objects.using(database)
            .filter(order_id=order.pk)
            .order_by("product_id", "pk")
        )
        quantities = {}
        for item in items:
            quantities[item.product_id] = (
                quantities.get(item.product_id, 0) + item.quantity
            )
        if not quantities:
            continue

        products = {
            product.pk: product
            for product in Product.objects.using(database).filter(
                pk__in=quantities
            )
        }
        if len(products) != len(quantities) or any(
            products[product_id].stock < quantity
            for product_id, quantity in quantities.items()
        ):
            continue

        for product_id, quantity in quantities.items():
            Product.objects.using(database).filter(pk=product_id).update(
                stock=models.F("stock") - quantity
            )
        Order.objects.using(database).filter(pk=order.pk).update(
            inventory_deducted=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sklepzdoniczkami', '0005_rename_tables_to_sklepzdoniczkami'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(reserve_existing_pending_orders),
    ]
