version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_ENV: production
    depends_on:
      - db

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: sklep_dev
      POSTGRES_USER: sklep
      POSTGRES_PASSWORD: sklep_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
