services:
  db:
    image: postgres:18
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_DB: sklepzdoniczkami_dev
      POSTGRES_USER: sklepzdoniczkami
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sklepzdoniczkami_dev_pass}
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
