services:
  - type: web
    name: sklep-internetowy
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "antczak.com.pl,www.antczak.com.pl,sklep.antczak.com.pl,.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://antczak.com.pl,https://www.antczak.com.pl,https://sklep.antczak.com.pl"
      - key: SITE_NAME
        value: "Sklep z Doniczkami"
      - key: DATABASE_URL
        fromDatabase:
          name: sklepdb
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: sklepdb
    databaseName: sklepdb
    user: sklepuser
    plan: free
