"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import re
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APP_ENV_FROM_ENV = os.environ.get('APP_ENV')
load_dotenv(BASE_DIR / '.env')

def env_value(name, default=None):
    return os.environ.get(f'{name}_{ENV_SUFFIX}', default)


def resolve_app_env(app_env: str | None, *, is_render: bool) -> str:
    if not app_env or not app_env.strip():
        if is_render:
            raise ImproperlyConfigured('APP_ENV must be explicitly configured on Render.')
        app_env = 'development'

    resolved_app_env = app_env.strip().lower()
    if resolved_app_env not in {'development', 'preprod', 'production'}:
        raise ImproperlyConfigured('APP_ENV must be development, preprod, or production.')
    return resolved_app_env


IS_RENDER = any(
    os.environ.get(name) for name in ('RENDER', 'RENDER_SERVICE_ID', 'RENDER_EXTERNAL_URL')
)
APP_ENV = resolve_app_env(
    APP_ENV_FROM_ENV if IS_RENDER else os.environ.get('APP_ENV'),
    is_render=IS_RENDER,
)
ENV_SUFFIX = APP_ENV.upper()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_value(
    'DJANGO_SECRET_KEY',
    'django-insecure-ew3ox9x+(5*j2p5p9sbdk=y4%bc%g1x%ld)-mf#nwv^s%+@wce',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',') if os.environ.get('ALLOWED_HOSTS') else ['*']
if APP_ENV in {'preprod', 'production'}:
    if not env_value('DATABASE_URL'):
        raise ImproperlyConfigured(f'DATABASE_URL_{ENV_SUFFIX} is required.')
    if not env_value('DJANGO_SECRET_KEY'):
        raise ImproperlyConfigured(f'DJANGO_SECRET_KEY_{ENV_SUFFIX} is required.')
    if DEBUG:
        raise ImproperlyConfigured(f'DEBUG must be False when APP_ENV={APP_ENV}.')
    if not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS:
        raise ImproperlyConfigured(f'ALLOWED_HOSTS must be explicitly configured when APP_ENV={APP_ENV}.')

if env_value('DATABASE_URL'):
    actual_database_name = dj_database_url.parse(env_value('DATABASE_URL'))['NAME']
    expected_database_name = env_value('DATABASE_NAME')
    if APP_ENV in {'preprod', 'production'} and not expected_database_name:
        raise ImproperlyConfigured(
            f'DATABASE_NAME_{ENV_SUFFIX} is required when DATABASE_URL_{ENV_SUFFIX} is set.'
        )
    if expected_database_name and actual_database_name != expected_database_name:
        raise ImproperlyConfigured(
            f'DATABASE_URL_{ENV_SUFFIX} must point to the '
            f'{expected_database_name} database.'
        )

CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS', 'http://localhost,https://localhost'
).split(',')

SITE_NAME = os.environ.get('SITE_NAME', 'Sklepzdoniczkami')

# When running behind Render's proxy, requests arrive over HTTP internally but
# were made over HTTPS by the client. This header tells Django to trust that.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

def validate_stripe_configuration(app_env, secret_key, public_key, webhook_secret):
    secret_key, public_key, webhook_secret = (
        secret_key.strip(),
        public_key.strip(),
        webhook_secret.strip(),
    )
    keys = (secret_key, public_key, webhook_secret)
    if not any(keys):
        return False
    if not all(keys):
        raise ImproperlyConfigured(
            f'Configure all three STRIPE_*_{app_env.upper()} secrets or leave them all unset.'
        )
    if not webhook_secret.startswith('whsec_'):
        raise ImproperlyConfigured(
            f'STRIPE_WEBHOOK_SECRET_{app_env.upper()} must be a Stripe webhook secret.'
        )

    expected_prefixes = {
        'preprod': ('sk_test_', 'pk_test_'),
        'production': ('sk_live_', 'pk_live_'),
    }
    allowed_prefixes = expected_prefixes.get(app_env)
    if allowed_prefixes:
        valid_mode = secret_key.startswith(allowed_prefixes[0]) and public_key.startswith(
            allowed_prefixes[1]
        )
    else:
        valid_mode = (
            secret_key.startswith('sk_test_') and public_key.startswith('pk_test_')
        ) or (
            secret_key.startswith('sk_live_') and public_key.startswith('pk_live_')
        )
    if not valid_mode:
        mode = 'test-mode' if app_env == 'preprod' else (
            'live-mode' if app_env == 'production' else 'matching test- or live-mode'
        )
        raise ImproperlyConfigured(f'{app_env} must use Stripe {mode} keys.')
    return True


STRIPE_SECRET_KEY = env_value('STRIPE_SECRET_KEY', '').strip()
STRIPE_PUBLIC_KEY = env_value('STRIPE_PUBLIC_KEY', '').strip()
STRIPE_WEBHOOK_SECRET = env_value('STRIPE_WEBHOOK_SECRET', '').strip()
STRIPE_ENABLED = validate_stripe_configuration(
    APP_ENV,
    STRIPE_SECRET_KEY,
    STRIPE_PUBLIC_KEY,
    STRIPE_WEBHOOK_SECRET,
)

# Application definition

INSTALLED_APPS = [
    'sklepzdoniczkami',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

LOGIN_URL = 'sklepzdoniczkami:login'
LOGIN_REDIRECT_URL = 'sklepzdoniczkami:profile'
LOGOUT_REDIRECT_URL = 'sklepzdoniczkami:home'

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        env=f'DATABASE_URL_{ENV_SUFFIX}',
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}

TEST_DATABASE_NAME = os.environ.get('DJANGO_TEST_DATABASE_NAME')
if TEST_DATABASE_NAME:
    if len(TEST_DATABASE_NAME) > 63 or not re.fullmatch(
        r'[A-Za-z_][A-Za-z0-9_]*', TEST_DATABASE_NAME
    ):
        raise ImproperlyConfigured('DJANGO_TEST_DATABASE_NAME must be a valid PostgreSQL identifier.')
    DATABASES['default']['TEST'] = {'NAME': TEST_DATABASE_NAME}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (user-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@sklepzdoniczkami.pl')
